#!/bin/sh

## set debug config files

LIVE_CONFIG_CMDLINE="${LIVE_CONFIG_CMDLINE:-$(cat /proc/cmdline)}"

_DEBUG=

for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
do
	case "${_PARAMETER}" in
		debug)
			_DEBUG="1"
			;;
	esac
done

echo "debug-generator: debug=${_DEBUG}"

# journald.conf

if [ "${_DEBUG}" = "1" ] 
then
	cat > /etc/systemd/journald.conf << EOF
[Journal]
Storage=auto	
EOF
else 
	cat > /etc/systemd/journald.conf << EOF
[Journal]
Storage=none
EOF
fi

exit $?
