#!/bin/sh

## enable netpoint systemd custom services within certain runlevels (early user-space)

## Enable the services with systemd.preset (https://www.freedesktop.org/software/systemd/man/systemd.preset.html) does not work

ln -sf /etc/systemd/system/rtc.service /etc/systemd/system/basic.target.wants/
ln -sf /etc/systemd/system/rtc-tgz.service /etc/systemd/system/basic.target.wants/
ln -sf /etc/systemd/system/set-time.service /etc/systemd/system/multi-user.target.wants/
ln -sf /etc/systemd/system/dhclient.service /etc/systemd/system/multi-user.target.wants/
exit $?
