#!/bin/sh

## live-config(7) - System Configuration Components
## Copyright (C) 2006-2014 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.

set -e

. /etc/environment

Cmdline ()
{
	# Reading kernel command line
	for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.user-default-groups=*|user-default-groups=*)
				LIVE_USER_DEFAULT_GROUPS="${_PARAMETER#*user-default-groups=}"
				;;

			live-config.user-fullname=*|user-fullname=*)
				LIVE_USER_FULLNAME="${_PARAMETER#*user-fullname=}"
				;;

			live-config.username=*|username=*)
				LIVE_USERNAME="${_PARAMETER#*username=}"
				;;
		esac
	done
}

Init ()
{
	echo -n "Init"
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/user-setup.list ] || \
	   [ -e /var/lib/live/config/user-setup ]
	then
		exit 0
	fi

	echo -n " user-setup"
}

Config ()
{
	echo -n "Config"
	# Checking if package is already configured differently
	if grep -q "^${LIVE_USERNAME}:" /etc/passwd
	then
		exit 0
	fi
	#echo "1"
	# Adjust formating of groups
	if [ -n "${LIVE_USER_DEFAULT_GROUPS}" ]
	then
		LIVE_USER_DEFAULT_GROUPS="$(echo ${LIVE_USER_DEFAULT_GROUPS} | sed -e 's|,| |g')"
	fi
	#echo "2"
	# Make sure user is not in sudo group if sudo is disabled
	case "${LIVE_CONFIG_NOROOT}" in
		true)
			LIVE_USER_DEFAULT_GROUPS="$(echo ${LIVE_USER_DEFAULT_GROUPS} | sed -e 's|sudo||')"
			;;
	esac
	
	#echo "3"
	# Default password is: live
	# passwords can be generated with 'echo "live" | mkpasswd -s',
	
	# _LIVE (default and disable empty password login in /etc/pam/common-auth: removed "nullok_secure")
	_LIVE='8Ab05sVQ4LLps'
	_EMPTY='U6aMy0wojraho'
	_PASSWORD="${_LIVE}"
	if [ ! -z "${xrootpwd}" ] 
	then
		_PASSWORD="${xrootpwd}"
	fi 
	
cat > /tmp/live-config.cfg << EOF
user-setup passwd/make-user boolean true
user-setup passwd/root-password-crypted string *
user-setup passwd/user-password-crypted string *
user-setup passwd/user-default-groups string ${LIVE_USER_DEFAULT_GROUPS}
user-setup passwd/user-fullname string ${LIVE_USER_FULLNAME}
user-setup passwd/username string ${LIVE_USERNAME}
user-setup passwd/user-uid string 1000
EOF

	debconf-set-selections < /tmp/live-config.cfg
	rm -f /tmp/live-config.cfg

	# Workaround for bug in shadow
	set +e
	/usr/lib/user-setup/user-setup-apply 2>&1 \
	| grep -v "Shadow passwords are now on"
	set -e
	
	# assign root password
	if [ ! -z "${xrootpwd}" ] 
	then
		echo "root:${_PASSWORD}" | chpasswd -e
	fi
	
	# Creating state file
	touch /var/lib/live/config/user-setup
}

Cmdline
Init
Config
