#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2013 Daniel Baumann <daniel@debian.org>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.

set -e

. /etc/environment

MountNFSData ()
{
	if [ ! -z "${xnfsdata}" ]
	then
		mount "${xnfsdata}" /data 
	fi
}

MountNFSData
